name: iPhoneCleaner
options:
  bundleIdPrefix: com.svetlana
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "16.0"

targets:
  iPhoneCleaner:
    type: application
    platform: iOS
    sources:
      - iPhoneCleaner
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "iPhone Cleaner needs access to your photo library to find duplicates, blurry photos, and screenshots for cleanup."
        INFOPLIST_KEY_NSPhotoLibraryAddUsageDescription: "iPhone Cleaner needs write access to move selected photos to Recently Deleted."
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        INCREASED_MEMORY_LIMIT: YES

  iPhoneCleanerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - iPhoneCleanerTests
    settings:
      base:
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: iPhoneCleaner

  iPhoneCleanerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - iPhoneCleanerUITests
    settings:
      base:
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: iPhoneCleaner
